name: Update README files

on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  schedule:
    - cron: '30 */2 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Get the latest READMEs
      run: wget "https://raw.githubusercontent.com/TheAwesomeCoder05/TheAwesomeCoder05/main/README.md" 
    - run: wget "https://cj.rs/riss.awk"
    - run: awk -f riss.awk README.md > ./docs/index.md
    - name: Commit and push if there are changes
      run: |-
        git diff
        git config --global user.email "hi@devcomp.tk"
        git config --global user.name "automaton"
        git diff --quiet || (git add -u && git commit -m "Update READMEs")
        git push        
