name: Make site

on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  schedule:
    # Runs at 2 UTC everyday
    - cron: "0 2 * * *"

jobs:
  update:
    name: Update site embed
    runs-on: ubuntu-latest
    steps:
      - name: Make site
        run: wget "https://raw.githubusercontent.com/TheAwesomeCoder05/TheAwesomeCoder05/main/README.md" | awk -f riss.awk README.md
